"""rename rentals table

Revision ID: 8c1dc02edfa7
Revises: 2e6807ee7ded
Create Date: 2023-01-05 17:16:19.382839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1dc02edfa7'
down_revision = '2e6807ee7ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customer_video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_video',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='customer_video_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='customer_video_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_video_pkey')
    )
    op.drop_table('rentals')
    # ### end Alembic commands ###
