"""update relationships

Revision ID: bee1f9af5c8f
Revises: 8c1dc02edfa7
Create Date: 2023-01-05 18:00:46.547570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee1f9af5c8f'
down_revision = '8c1dc02edfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rentals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='rentals_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='rentals_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rentals_pkey')
    )
    op.drop_table('customer_video')
    # ### end Alembic commands ###
